variables:
#    TEMPLATE_DISABLE: "1"
    TEMPLATE_DEB_NAME: "unipi-kernel-modules"

include: 
    project: docker/template
    file: debian-pkg.yaml

##############################################################
build-newstable:nano:
    extends: .build_for_newstable
    tags: ['arm64']
    before_script: 
        - apt-get update
        - apt-get install -y axon-kernel-headers

build-newstable:rpi:
    extends: .build_for_newstable
    tags: ['armhf']
    #before_script: 
    #    - apt-get update
    #    - apt-get install -y raspberrypi-kernel-headers

build-stable:nano:
    extends: .build_for_stable
    tags: ['arm64']
    before_script: 
        - apt-get update
        - apt-get install -y axon-kernel-headers

build-stable:rpi:
    extends: .build_for_stable
    tags: ['armhf']
    #before_script: 
    #    - apt-get update
    #    - apt-get install -y raspberrypi-kernel-headers

build-oldstable:nano:
    extends: .build_for_oldstable
    tags: ['arm64']
    before_script: 
        - apt-get update
        - apt-get install -y axon-kernel-headers

build-oldstable:rpi:
    extends: .build_for_oldstable
    tags: ['armhf']
    #before_script: 
    #    - apt-get update
    #    - apt-get install -y raspberrypi-kernel-headers

deploy-test:
    extends: .deploy_test

deploy-release:
    extends: .deploy_master
